export * from './category.repository';
export * from './ecom.repository';
export * from './city.repository';
export * from './region.repository';
export * from './product.repository';
export * from './student.repository';
export * from './course.repository';
export * from './department.repository';
export * from './address.repository';
